Tune the torso position PID for iCubGazeboV3
robotology/icub-models pull request #63
Opened 2020-10-23 16:29 UTC by GiulioRomualdi

2020-10-23 17:44 UTC, traversaro approved these changes

2020-10-23 17:45 UTC, traversaro requested changes
This files are automatically generated, the corresponding file is https://github.com/robotology/icub-model-generator/blob/master/simmechanics/data/icub3/conf/gazebo_icub_torso.ini .

2020-10-23 18:51 UTC, GiulioRomualdi commented
Ops I didn't know

2020-10-24 12:24 UTC, GiulioRomualdi commented
I opened a new PR in `icub-model-generator` https://github.com/robotology/icub-model-generator/pull/152.
We can close this one

2020-10-24 12:24 UTC, closed without merging